@echo off
cd /d "D:\programs\5-star-rating\rating-app-testing"
echo Starting Firebase emulators in background...
start /min "FirebaseEmulators" cmd /c "firebase emulators:start --only firestore,auth --project star-rating-83004"
echo Waiting 20 seconds for emulators to start...
timeout /t 20 /nobreak
echo Running security rules tests...
cd /d "D:\programs\5-star-rating\rating-app-testing\backend\functions"
node rules-test.js
echo.
echo Tests complete. Shutting down emulators...
taskkill /F /IM java.exe 2>nul
